#项目相关配置
ssm:
  version: 1.0.0

#jdbc 配置
spring:
  #多环境配置
  profiles:
    active: @profileActive@
#  mvc:
#    view:w
#      #默认前缀
#      prefix:
#      #响应页面默认后缀
#      suffix: .html
#使用springboot自带的activemq，所以注释了下面的activemq配置
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin

#mybats配置
mybatis:
  mapper-locations:  classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: tk.mybatis.springboot.model
  configLocation: classpath:mybatis/mybatis-config.xml
mapper:
  mappers:
    # 每个mapper文件都需要在这里添加
    - cn.xyr.ssm.dao.mapper.UserMapper
  not-empty: false
  identity: MYSQL
